server:
  #用于注册服务的端口号
  port: 10209
spring:
  application:
    #用于注册服务的项目名称
    name: tracer
  #配置redis
  redis:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    url: redis://user:@127.0.0.1:6379
  data:
    # 配置mongodb
    mongodb:
      uri: mongodb://root:rootroot@localhost:27017/tracer

